# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # allow manual trigger  
  workflow_dispatch:

jobs:
  test-python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz attrs pytest
      - name: build and install
        run:
          pip install .
      - name: Test with pytest
        run: |
          pytest -v tests

  test-dotnet:
    name: build, pack, test .Net
    runs-on: ubuntu-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Install .Net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore, Build, test, and pack
        uses: Elskom/build-dotnet@main
        with:
          SOLUTION_FILE_PATH: 'dotnet/Serpent'
          TEST: true
          PACK: true
          PUSH: false

  test-java:
    name: build, test Java
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -f java/pom.xml verify
