# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# TODO add Java and C# test runs as well
# below is the snippet from travis that used to do this:
#- language: java
#  # jdk:
#  #  - oraclejdk8
#  script: mvn -f java/pom.xml verify
#  cache:
#    directories:
#      - '$HOME/.m2/repository'
#
#- language: csharp
#  dotnet: 2.2
#  mono: none
#  script:
#    - dotnet restore dotnet/Serpent
#    - dotnet test dotnet/Serpent/Tests


name: Run CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  # allow manual trigger  
  workflow_dispatch:

jobs:
  test-python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
        
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz attrs pytest
      - name: build and install
        run:
          pip install .
      - name: Test with pytest
        run: |
          pytest -v tests

  test-dotnet:
    name: build, pack, test .Net
    runs-on: ubuntu-latest
    env:
      SOLUTION_FILE_PATH: 'dotnet/Serpent'
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Install latest .NET SDK
        uses: Elskom/setup-latest-dotnet@main

      - name: Restore, Build, test, and pack
        uses: Elskom/build-dotnet@main
        with:
          TEST: true
          PACK: true
          PUSH: false
